### ISSUE TITLE
dockerfile fails to create an image

### ISSUE THREAD

**Issue by shantanuo** [EagleChen/docker_go_mysql_elasticsearch#3]
When I forked your repo, I get the following error while building image using dockerfile

Build failed: The command '/bin/sh -c apt-get update && apt-get install -y --force-yes mariadb-client=$MARIADB_VERSION && go get github.com/tools/godep && (go get github.com/siddontang/go-mysql-elasticsearch || true ) && cd /go/src/github.com/siddontang/go-mysql-elasticsearch && make' returned a non-zero code: 100

I wonder how your automated build is successful while this one fails.

**Comment by EagleChen** [comment]
@shantanuo 
To answer your question, `github.com/siddontang/go-mysql-elasticsearch` has changed a lot since I built the image. I should have freeze the `version` of it, then there would be no problem.
That's to say, if you use an older version of it, the build should pass.

How to fix it:
use golang:1.6 as the base image ( as documented in the readme of its repo )

However I have not tried it yet. Will try it later and keep you updated :)

**Comment by EagleChen** [comment]
@shantanuo 

It turns out that mariadb package has also been updated.
I've updated the Dockerfile and pushed a new commit. You can use this latest Dockerfile to build the image by yourself.
Or you can download it from dockerhub.
I will close this issue for now.

If you have other questions, please feel free to reopen it.
